version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install the Amazon Linux Extras repo
      - yum install -y amazon-linux-extras-1.6.13

      # Install gcc
      - yum install -y gcc-7.3.1

      # Update pip
      - python3.8 -m pip install --upgrade pip==21.0.1

      # Install pip packages
      - python3.8 -m pip install -r requirements/common.txt

  pre_build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.djangoproject.com/en/3.1/topics/testing/overview/>
      - /home/ec2-user/generateenv.sh
      - python3.8 manage.py test

  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN in template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json

artifacts:
  files:
    - 'template.yml'
    - 'folder/**/*'
    - 'files/**/*'
    - 'users/**/*'
    - 'scripts/**/*'
    - 'appspec.yml'
    - 'manage.py'
    - 'requirements/**/*'
    - 'requirements.txt'
    - 'supervisord.conf'
    - 'template-configuration.json'
    -  '.env'
